version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./viatab-frontend
      dockerfile: Dockerfile
    image: viatab-frontend
    container_name: viatab-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: 
      context: ./App
      dockerfile: Dockerfile
    image: viatab-backend
    container_name: viatab-backend
    ports:
      - "5171:5171"
    environment:
      ASPNETCORE_URLS: http://+:5171
      DB_CONNECTION_STRING: Host=db;Port=5432;Database=postgres;Username=postgres;Password=password
    depends_on:
      - db

volumes:
  db_data:
